const columnList = [
  {
    field: 'position',
    header: '',
    showFilterMenu: false,
    sortable: false,
    filter: false,
    showClearButton: false,
    filterPlaceholder: '',
  },
  {
    field: 'name',
    header: 'Name',
    showFilterMenu: false,
    sortable: false,
    filter: false,
    showClearButton: false,
    filterPlaceholder: '',
  },
  {
    field: 'records',
    header: 'Records',
    showFilterMenu: false,
    sortable: false,
    filter: false,
    showClearButton: false,
    filterPlaceholder: '',
  },
  {
    field: 'coreTeam',
    header: 'Core Team',
    showFilterMenu: false,
    sortable: false,
    filter: false,
    showClearButton: false,
    filterPlaceholder: '',
  },
  {
    field: 'season',
    header: 'Season Q',
    showFilterMenu: false,
    sortable: false,
    filter: false,
    showClearButton: false,
    filterPlaceholder: '',
  },
];
const userTableData = [
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 1,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 2,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 3,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 4,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 5,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 6,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 7,
    coreTeam: '',
  },
  {
    name: 'Patrick Marlin',
    records: '',
    season: 'CUS99638013',
    position: 8,
    coreTeam: '',
  },
];
export { columnList, userTableData };
