const sideBarMenu = [
  {
    label: 'Dashboard',
    icon: 'pi-home',
    relativePath: 'doctor',
    path: '',
    component: 'Dashboard',
  },
  {
    label: 'Patient Information',
    icon: 'pi-home',
    relativePath: 'doctor',
    path: 'patient-information',
    component: 'PatientInformation',
  },
  {
    label: 'MSK Care Portal',
    icon: 'pi-chart-bar',
    relativePath: 'doctor',
    path: 'care-portal',
    component: 'CarePortal',
  },
  {
    label: 'Profile',
    icon: ' pi-user',
    relativePath: 'doctor',
    path: 'profile',
    component: 'Profile',
  },
  {
    label: 'Documents',
    icon: 'pi-file',
    relativePath: 'doctor',
    path: 'documents',
    component: 'Documents',
  },
  {
    label: 'Appointment',
    icon: 'pi-plus',
    relativePath: 'doctor',
    path: 'appointment',
    component: 'Appointment',
  },
  {
    label: 'Community',
    icon: 'pi-users',
    relativePath: 'doctor',
    path: 'community',
    component: 'Community',
  },
  {
    label: 'Orthopedic Specialists',
    icon: 'pi-heart-fill',
    relativePath: 'doctor',
    path: 'orthopedic-specialists',
    component: 'OrthopedicSpecialists',
  },
  {
    label: 'Video Call',
    icon: 'pi-video',
    relativePath: 'doctor',
    path: 'call',
    component: 'AppointmentVideoApp',
  },
  {
    label: 'Doctor Profile',
    icon: 'pi-user-plus',
    relativePath: 'doctor',
    path: 'doctor-profile',
    component: 'DoctorProfileApp',
  },
  {
    label: 'Care Team',
    icon: 'pi-check-circle',
    relativePath: 'doctor',
    path: 'team',
    component: 'CareTeamApp',
  },
  {
    label: 'Community Chat',
    icon: 'pi-user-plus',
    relativePath: 'doctor',
    path: 'community-chat',
    component: 'CommunityChat',
  },
];

const phnCodes = [
  { name: 'Canada', code: 'CA', phnCode: '+1' },
  { name: 'United States', code: 'US', phnCode: '+1' },
  { name: 'Russia', code: 'RU', phnCode: '+7' },
  { name: 'Egypt', code: 'EG', phnCode: '+20' },
  { name: 'South Africa', code: 'ZA', phnCode: '+27' },
  { name: 'Greece', code: 'GR', phnCode: '+30' },
  { name: 'Netherlands', code: 'NL', phnCode: '+31' },
  { name: 'France', code: 'FR', phnCode: '+33' },
  { name: 'Spain', code: 'ES', phnCode: '+34' },
  { name: 'Hungary', code: 'HU', phnCode: '+36' },
  { name: 'Italy', code: 'IT', phnCode: '+39' },
  { name: 'Romania', code: 'RO', phnCode: '+40' },
  { name: 'Switzerland', code: 'CH', phnCode: '+41' },
  { name: 'United Kingdom', code: 'GB', phnCode: '+44' },
  { name: 'Sweden', code: 'SE', phnCode: '+46' },
  { name: 'Norway', code: 'NO', phnCode: '+47' },
  { name: 'Germany', code: 'DE', phnCode: '+49' },
  { name: 'Peru', code: 'PE', phnCode: '+51' },
  { name: 'Mexico', code: 'MX', phnCode: '+52' },
  { name: 'Argentina', code: 'AR', phnCode: '+54' },
  { name: 'Brazil', code: 'BR', phnCode: '+55' },
  { name: 'Chile', code: 'CL', phnCode: '+56' },
  { name: 'Colombia', code: 'CO', phnCode: '+57' },
  { name: 'Malaysia', code: 'MY', phnCode: '+60' },
  { name: 'Australia', code: 'AU', phnCode: '+61' },
  { name: 'Indonesia', code: 'ID', phnCode: '+62' },
  { name: 'Philippines', code: 'PH', phnCode: '+63' },
  { name: 'Singapore', code: 'SG', phnCode: '+65' },
  { name: 'Thailand', code: 'TH', phnCode: '+66' },
  { name: 'Japan', code: 'JP', phnCode: '+81' },
  { name: 'South Korea', code: 'KR', phnCode: '+82' },
  { name: 'Vietnam', code: 'VN', phnCode: '+84' },
  { name: 'China', code: 'CN', phnCode: '+86' },
  { name: 'Turkey', code: 'TR', phnCode: '+90' },
  { name: 'India', code: 'IN', phnCode: '+91' },
  { name: 'Pakistan', code: 'PK', phnCode: '+92' },
  { name: 'Afghanistan', code: 'AF', phnCode: '+93' },
  { name: 'Algeria', code: 'DZ', phnCode: '+213' },
  { name: 'Nigeria', code: 'NG', phnCode: '+234' },
  { name: 'Portugal', code: 'PT', phnCode: '+351' },
  { name: 'Ireland', code: 'IE', phnCode: '+353' },
  { name: 'Albania', code: 'AL', phnCode: '+355' },
  { name: 'Finland', code: 'FI', phnCode: '+358' },
  { name: 'Ukraine', code: 'UA', phnCode: '+380' },
  { name: 'Czech Republic', code: 'CZ', phnCode: '+420' },
  { name: 'Bangladesh', code: 'BD', phnCode: '+880' },
  { name: 'Saudi Arabia', code: 'SA', phnCode: '+966' },
  { name: 'Israel', code: 'IL', phnCode: '+972' },
];

export const doctorData = {
  name: 'Dr. Alec Clemat',
  gender: 'Female Hybrid',
  languages: 'English/Spanish',
  speciality: 'Orthopedic Specialist',
  address: 'P 174 Suit 2110 Cypres TX 77024',
  address2: '718 Suite 2101 Wood Landol 77858',
  eduction: 'MBBS',
  ['Practice Names']: 'Houston Methodist',
  speciality2: 'Sports Medicine',
  ['Hospital Affiliation']: 'Hoaston Methodist',
  ['Education Training']: 'Baylor College of Medicine Houston Methodist',
  ['In Network Insurance']: 'Gigna, Aetna',
};

export const doctorProfileData = {
  name: 'Alec Jay',
  gender: 'Male',
  speciality1: 'Sports Medicine',
  address: 'P 174 Suit 2110 Cypres TX 77024',
  eduction: 'Baylor College of Medicine',
  ['Practice Names']: 'Houston Methodist Hospital',
  ['Hospital Affiliation']: 'Hoaston Methodist',
  training: 'Baylor College of Medicine',
  ['In Network Insurance']: 'Cigna',
  telehealth: 'Yes',
  ['Hybrid:(Inperson + Telehealth)']: 'Yes',
  surgery: 'Yes',
  ['New Patient']: 'Yes',
};

export { sideBarMenu, phnCodes };
